// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKU16Hhy8g09A3gdR8VbGx_HNdgZXRHvA',
    appId: '1:645474708199:web:ae72838df37d4bb83d5042',
    messagingSenderId: '645474708199',
    projectId: 'nadi-bahrain-a2392',
    authDomain: 'nadi-bahrain-a2392.firebaseapp.com',
    storageBucket: 'nadi-bahrain-a2392.firebasestorage.app',
    measurementId: 'G-C74TTS2WQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGL28asijkLYdX6DhIhDKs99MbYShurTQ',
    appId: '1:645474708199:android:09b7c750e0c30d723d5042',
    messagingSenderId: '645474708199',
    projectId: 'nadi-bahrain-a2392',
    storageBucket: 'nadi-bahrain-a2392.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0H_uWRLhaQTc8oL7ORovzECYHEx9CAEI',
    appId: '1:645474708199:ios:eabcb124ae2bc1823d5042',
    messagingSenderId: '645474708199',
    projectId: 'nadi-bahrain-a2392',
    storageBucket: 'nadi-bahrain-a2392.firebasestorage.app',
    iosBundleId: 'com.hgtech.nadibh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0H_uWRLhaQTc8oL7ORovzECYHEx9CAEI',
    appId: '1:645474708199:ios:eabcb124ae2bc1823d5042',
    messagingSenderId: '645474708199',
    projectId: 'nadi-bahrain-a2392',
    storageBucket: 'nadi-bahrain-a2392.firebasestorage.app',
    iosBundleId: 'com.hgtech.nadibh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKU16Hhy8g09A3gdR8VbGx_HNdgZXRHvA',
    appId: '1:645474708199:web:6d8aa240937e02153d5042',
    messagingSenderId: '645474708199',
    projectId: 'nadi-bahrain-a2392',
    authDomain: 'nadi-bahrain-a2392.firebaseapp.com',
    storageBucket: 'nadi-bahrain-a2392.firebasestorage.app',
    measurementId: 'G-G1K1NBQLQQ',
  );
}
